spring.application.name=ar-service
server.port=8081
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Environment variable
jwt.secret=${JWT_SECRET}                   
jwt.expiration=3600000