spring.application.name=correspondence-service
server.port=8087

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
# Environment variable
spring.mail.password=${SENDGRID_API_KEY}   
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Environment variable
jwt.secret=${JWT_SECRET}                   
jwt.expiration=3600000
