spring.application.name=reports-service
server.port=8089
# application.properties
reports.output.dir=D:/HIS/Sharepoint/Reports
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
logging.level.org.springframework.security=DEBUG



